name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/hikari.fish
            sudo rm -rf *
            sudo cp -R $GITHUB_WORKSPACE/dist/* /var/www/hikari.fish
            sudo chown -R www-data:www-data /var/www/hikari.fish
            sudo systemctl restart nginx
